# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Deploy server

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build/Release the Docker image
      run: |
        cd server
        docker login ${{ secrets.Docker_Registry }} -u ${{ secrets.Docker_User }} -p ${{ secrets.Docker_Pass }}
        docker build -t ${{ secrets.Docker_Registry }}/ctracker:latest .
        docker push ${{ secrets.Docker_Registry }}/ctracker:latest
    
    - name: Deploy the Docker image to rancher
      uses: sekassel-research/actions-rancher-update@1.1.1
      with:
        rancher_url: ${{ secrets.Rancher_Url }}
        rancher_access: ${{ secrets.Rancher_Access }}
        rancher_key: ${{ secrets.Rancher_Key }}
        project_id: ${{ secrets.Project_Id }}
        stack_name: ${{ secrets.Stack_Name }}
        service_name: ${{ secrets.Service_Name }}
        docker_image: ${{ secrets.Docker_Registry }}/ctracker:latest
