name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO build
      run: pio run -t buildfs --project-dir ./tracker

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./esp32/tracker/.pio/build/*/firmware.bin
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
